<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Reset cached roles and permissions
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        // Create permissions
        $permissions = [
            // Dashboard
            'view dashboard',
            'view statistics',
            'view charts',
            'export dashboard data',

            // User management
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'force delete users',
            'import users',
            'export users',

            // Role management
            'view roles',
            'create roles',
            'edit roles',
            'delete roles',
            'assign roles',

            // Permission management
            'view any permissions',
            'view permissions',
            'create permissions',
            'edit permissions',
            'delete permissions',
            'restore permissions',
            'force delete permissions',
            'assign permissions',

            // Profile management
            'view own profile',
            'edit own profile',
            'delete own profile',
            'change own password',
            'view other profiles',

            // Settings
            'view settings',
            'edit settings',
            'view system settings',
            'edit system settings',
            'view security settings',
            'edit security settings',

            // Notifications
            'view notifications',
            'create notifications',
            'edit notifications',
            'delete notifications',
            'send notifications',

            // Activity logs
            'view any activity logs',
            'view activity logs',
            'export activity logs',
            'delete activity logs',

            // Reports
            'view reports',
            'create reports',
            'edit reports',
            'delete reports',
            'export reports',
            'schedule reports',

            // File management
            'view files',
            'upload files',
            'download files',
            'delete files',
            'restore files',
            'force delete files',

            // Audit trail
            'view audit trail',
            'export audit trail',

            // Backup
            'view backups',
            'create backups',
            'restore backups',
            'delete backups',
            'import backups',
            'export backups',

            // API access
            'view api keys',
            'create api keys',
            'revoke api keys',
            'view api logs',

            // System maintenance
            'clear cache',
            'view system info',
            'run maintenance',
            'view logs',

            // Contact information
            'view any contact information',
            'view contact information',
            'create contact information',
            'edit contact information',
            'delete contact information',
            'restore contact information',
            'force delete contact information',
            'import contact information',
            'export contact information',
            'merge contacts',

            // Task status management
            'view task statuses',
            'create task statuses',
            'edit task statuses',
            'delete task statuses',
            'restore task statuses',
            'force delete task statuses',
            'import task statuses',
            'export task statuses',
            'assign task statuses',

            // Task management
            'view any task',
            'view task',
            'create task',
            'edit task',
            'delete task',
            'restore task',
            'force delete task',
            'import task',
            'export task',
            'assign task',
            'change task status',

            // Order status management
            'view order statuses',
            'create order statuses',
            'edit order statuses',
            'delete order statuses',
            'restore order statuses',
            'force delete order statuses',
            'import order statuses',
            'export order statuses',
            'assign order statuses',

            // Order management
            'view any order',
            'view order',
            'create order',
            'edit order',
            'delete order',
            'restore order',
            'force delete order',
            'import order',
            'export order',
            'assign order',
            'change order status',

            // Industry management
            'view industries',
            'create industries',
            'edit industries',
            'delete industries',
            'restore industries',
            'force delete industries',
            'import industries',
            'export industries',
            'assign industries',

            // Company management
            'view companies',
            'create companies',
            'edit companies',
            'delete companies',
            'restore companies',
            'force delete companies',
            'import companies',
            'export companies',
            'change company industry',
            'merge companies',

            // Plan management
            'view any plans',
            'view plans',
            'create plans',
            'edit plans',
            'delete plans',
            'restore plans',
            'force delete plans',

            // Address Management
            'view any addresses',
            'view addresses',
            'create addresses',
            'edit addresses',
            'delete addresses',
            'force delete addresses',
            'restore addresses',
            'import addresses',
            'export addresses',
            'assign address',

            // Category Management
            'view any categories',
            'view categories',
            'create categories',
            'edit categories',
            'delete categories',
            'restore categories',
            'force delete categories',
            'import categories',
            'export categories',
            'assign category',

            // Post Management
            'view any posts',
            'view posts',
            'create posts',
            'edit posts',
            'delete posts',
            'restore posts',
            'force delete posts',
            'import posts',
            'export posts',

            // Comment Management
            'view any comments',
            'view comments',
            'create comments',
            'edit comments',
            'delete comments',
            'restore comments',
            'force delete comments',
            'import comments',
            'export comments',

            // Tag Management
            'view any tags',
            'view tags',
            'create tags',
            'update tags',
            'delete tags',
            'restore tags',
            'force delete tags',
            'import tags',
            'export tags',

            // Invoice status management
            'view invoice statuses',
            'create invoice statuses',
            'edit invoice statuses',
            'delete invoice statuses',
            'restore invoice statuses',
            'force delete invoice statuses',
            'import invoice statuses',
            'export invoice statuses',
            'assign invoice statuses',

            // Registeration Interests management
            'view any registration interests',
            'view registration interests',
            'delete registration interests',
            'restore registration interests',
            'force delete registration interests',
            'export registration interests',

            // Invoice management
            'view any invoice',
            'view invoice',
            'create invoice',
            'edit invoice',
            'delete invoice',
            'restore invoice',
            'force delete invoice',
            'import invoice',
            'export invoice',
            'assign invoice',
            'change invoice status',
            'send invoices',
            'mark invoices as paid',
            'mark invoice as unpaid',

            // Invoice item management
            'view any invoice item',
            'view invoice item',
            'create invoice item',
            'edit invoice item',
            'delete invoice item',
            'restore invoice item',
            'force delete invoice item',
            'import invoice item',
            'export invoice item',

            // Pipeline status management
            'view pipeline statuses',
            'create pipeline statuses',
            'edit pipeline statuses',
            'delete pipeline statuses',
            'restore pipeline statuses',
            'force delete pipeline statuses',
            'import pipeline statuses',
            'export pipeline statuses',
            'assign pipeline statuses',

            // Pipeline management
            'view any pipeline',
            'view pipeline',
            'create pipeline',
            'edit pipeline',
            'delete pipeline',
            'restore pipeline',
            'force delete pipeline',
            'import pipeline',
            'export pipeline',
            'assign pipeline',
            'change pipeline status',

            // Pipeline stage management
            'view any pipeline stage',
            'view pipeline stage',
            'create pipeline stage',
            'edit pipeline stage',
            'delete pipeline stage',
            'restore pipeline stage',
            'force delete pipeline stage',
            'import pipeline stage',
            'export pipeline stage',
            'assign pipeline stage',

            // Deal status management
            'view deal statuses',
            'create deal statuses',
            'edit deal statuses',
            'delete deal statuses',
            'restore deal statuses',
            'force delete deal statuses',
            'import deal statuses',
            'export deal statuses',
            'assign deal statuses',

            // Deal management
            'view any deal',
            'view deal',
            'create deal',
            'edit deal',
            'delete deal',
            'restore deal',
            'force delete deal',
            'import deal',
            'export deal',
            'assign deal',
            'change deal status',

            // Ticket priority management
            'view ticket priorities',
            'create ticket priorities',
            'edit ticket priorities',
            'delete ticket priorities',
            'restore ticket priorities',
            'force delete ticket priorities',
            'import ticket priorities',
            'export ticket priorities',
            'assign ticket priorities',

            // Ticket status management
            'view ticket statuses',
            'create ticket statuses',
            'edit ticket statuses',
            'delete ticket statuses',
            'restore ticket statuses',
            'force delete ticket statuses',
            'import ticket statuses',
            'export ticket statuses',
            'assign ticket statuses',

            // Ticket management
            'view any ticket',
            'view ticket',
            'create ticket',
            'edit ticket',
            'delete ticket',
            'restore ticket',
            'force delete ticket',
            'import ticket',
            'export ticket',
            'assign ticket',
            'change ticket status',
            'change ticket priority',

            // Label Management
            'view any labels',
            'view labels',
            'create labels',
            'edit labels',
            'delete labels',
            'restore labels',
            'force delete labels',
            'import labels',
            'export labels',
            'assign labels',

            // Activity Management
            'view activities',
            'create activities',
            'delete activities',
            'restore activities',
            'force delete activities',
            'export activities',

            // Interaction log Management
            'create interaction logs',
            'update interaction logs',
            'delete interaction logs',
            'force delete interaction logs',

            // Calendar Management
            'view calendar',

            // Attachment Management
            'view any attachments',
            'view attachments',
            'create attachments',
            'delete attachments',
            'restore attachments',
            'force delete attachments',
            'download attachments',
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission]);
        }

        // Create roles and assign permissions

        // Super Admin role - has all permissions
        $superAdmin = Role::firstOrCreate(['name' => 'Super Admin']);
        $superAdmin->givePermissionTo(Permission::all());

        // Admin role - has most permissions except system-critical ones
        $admin = Role::firstOrCreate(['name' => 'Admin']);
        $adminPermissions = [
            'view dashboard',
            'view statistics',
            'view charts',
            'export dashboard data',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'restore users',
            'import users',
            'export users',
            'view roles',
            'create roles',
            'edit roles',
            'delete roles',
            'assign roles',
            'view any permissions',
            'view permissions',
            'create permissions',
            'edit permissions',
            'delete permissions',
            'restore permissions',
            'force delete permissions',
            'assign permissions',
            'view own profile',
            'edit own profile',
            'delete own profile',
            'change own password',
            'view other profiles',
            'view settings',
            'edit settings',
            'view notifications',
            'create notifications',
            'edit notifications',
            'delete notifications',
            'send notifications',
            'view any activity logs',
            'view activity logs',
            'export activity logs',
            'delete activity logs',
            'view reports',
            'create reports',
            'edit reports',
            'delete reports',
            'export reports',
            'schedule reports',
            'view files',
            'upload files',
            'download files',
            'delete files',
            'restore files',
            'view audit trail',
            'export audit trail',
            'view backups',
            'create backups',
            'restore backups',
            'delete backups',
            'import backups',
            'export backups',
            'view api keys',
            'create api keys',
            'revoke api keys',
            'view api logs',
            'clear cache',
            'view system info',
            'view logs',
            'view any contact information',
            'view contact information',
            'create contact information',
            'edit contact information',
            'delete contact information',
            'restore contact information',
            'import contact information',
            'export contact information',
            'merge contacts',
            'view task statuses',
            'create task statuses',
            'edit task statuses',
            'delete task statuses',
            'restore task statuses',
            'force delete task statuses',
            'import task statuses',
            'export task statuses',
            'assign task statuses',
            'view any task',
            'view task',
            'create task',
            'edit task',
            'delete task',
            'restore task',
            'import task',
            'export task',
            'assign task',
            'change task status',
            'view order statuses',
            'create order statuses',
            'edit order statuses',
            'delete order statuses',
            'restore order statuses',
            'force delete order statuses',
            'import order statuses',
            'export order statuses',
            'assign order statuses',
            'view any order',
            'view order',
            'create order',
            'edit order',
            'delete order',
            'restore order',
            'import order',
            'export order',
            'assign order',
            'change order status',
            'view industries',
            'create industries',
            'edit industries',
            'delete industries',
            'restore industries',
            'force delete industries',
            'import industries',
            'export industries',
            'assign industries',
            'view companies',
            'create companies',
            'edit companies',
            'delete companies',
            'restore companies',
            'force delete companies',
            'import companies',
            'export companies',
            'change company industry',
            'merge companies',
            'view any plans',
            'view plans',
            'create plans',
            'edit plans',
            'delete plans',
            'restore plans',
            'force delete plans',
            'view any addresses',
            'view addresses',
            'create addresses',
            'edit addresses',
            'delete addresses',
            'force delete addresses',
            'restore addresses',
            'import addresses',
            'export addresses',
            'assign address',
            'view any categories',
            'view categories',
            'create categories',
            'edit categories',
            'delete categories',
            'restore categories',
            'force delete categories',
            'import categories',
            'export categories',
            'assign category',
            'view any posts',
            'view posts',
            'create posts',
            'edit posts',
            'delete posts',
            'restore posts',
            'force delete posts',
            'import posts',
            'export posts',
            'view any comments',
            'view comments',
            'create comments',
            'edit comments',
            'delete comments',
            'restore comments',
            'force delete comments',
            'import comments',
            'export comments',
            'view any tags',
            'view tags',
            'create tags',
            'update tags',
            'delete tags',
            'restore tags',
            'import tags',
            'export tags',
            'force delete tags',
            'view invoice statuses',
            'create invoice statuses',
            'edit invoice statuses',
            'delete invoice statuses',
            'restore invoice statuses',
            'force delete invoice statuses',
            'import invoice statuses',
            'export invoice statuses',
            'assign invoice statuses',
            'view any registration interests',
            'view registration interests',
            'delete registration interests',
            'restore registration interests',
            'force delete registration interests',
            'export registration interests',
            'view any invoice',
            'view invoice',
            'create invoice',
            'edit invoice',
            'delete invoice',
            'restore invoice',
            'import invoice',
            'export invoice',
            'assign invoice',
            'change invoice status',
            'send invoices',
            'mark invoices as paid',
            'mark invoice as unpaid',
            'create invoice item',
            'edit invoice item',
            'delete invoice item',
            'restore invoice item',
            'import invoice item',
            'export invoice item',
            'view pipeline statuses',
            'create pipeline statuses',
            'edit pipeline statuses',
            'delete pipeline statuses',
            'restore pipeline statuses',
            'force delete pipeline statuses',
            'import pipeline statuses',
            'export pipeline statuses',
            'assign pipeline statuses',
            'view any pipeline',
            'view pipeline',
            'create pipeline',
            'edit pipeline',
            'delete pipeline',
            'restore pipeline',
            'import pipeline',
            'export pipeline',
            'assign pipeline',
            'change pipeline status',
            'view any pipeline stage',
            'view pipeline stage',
            'create pipeline stage',
            'edit pipeline stage',
            'delete pipeline stage',
            'restore pipeline stage',
            'import pipeline stage',
            'export pipeline stage',
            'assign pipeline stage',
            'view deal statuses',
            'create deal statuses',
            'edit deal statuses',
            'delete deal statuses',
            'restore deal statuses',
            'force delete deal statuses',
            'import deal statuses',
            'export deal statuses',
            'assign deal statuses',
            'view any deal',
            'view deal',
            'create deal',
            'edit deal',
            'delete deal',
            'restore deal',
            'force delete deal',
            'import deal',
            'export deal',
            'assign deal',
            'change deal status',
            'view ticket priorities',
            'create ticket priorities',
            'edit ticket priorities',
            'delete ticket priorities',
            'restore ticket priorities',
            'force delete ticket priorities',
            'import ticket priorities',
            'export ticket priorities',
            'assign ticket priorities',
            'view ticket statuses',
            'create ticket statuses',
            'edit ticket statuses',
            'delete ticket statuses',
            'restore ticket statuses',
            'force delete ticket statuses',
            'import ticket statuses',
            'export ticket statuses',
            'assign ticket statuses',
            'view any ticket',
            'view ticket',
            'create ticket',
            'edit ticket',
            'delete ticket',
            'restore ticket',
            'import ticket',
            'export ticket',
            'assign ticket',
            'change ticket status',
            'change ticket priority',
            'view any labels',
            'view labels',
            'create labels',
            'edit labels',
            'delete labels',
            'restore labels',
            'force delete labels',
            'import labels',
            'export labels',
            'assign labels',
            'view activities',
            'create activities',
            'delete activities',
            'restore activities',
            'export activities',
            'create interaction logs',
            'update interaction logs',
            'delete interaction logs',
            'force delete interaction logs',
            'view calendar',
            'view any attachments',
            'view attachments',
            'create attachments',
            'delete attachments',
            'restore attachments',
            'force delete attachments',
            'download attachments',
        ];
        $admin->givePermissionTo($adminPermissions);

        // Manager role - can manage content and users but limited system access
        $manager = Role::firstOrCreate(['name' => 'Manager']);
        $managerPermissions = [
            'view dashboard',
            'view statistics',
            'view charts',
            'export dashboard data',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'import users',
            'export users',
            'view roles',
            'assign roles',
            'view own profile',
            'edit own profile',
            'delete own profile',
            'change own password',
            'view other profiles',
            'view settings',
            'view notifications',
            'create notifications',
            'send notifications',
            'view any activity logs',
            'view activity logs',
            'export activity logs',
            'delete activity logs',
            'view reports',
            'create reports',
            'edit reports',
            'export reports',
            'view files',
            'upload files',
            'download files',
            'delete files',
            'view audit trail',
            'view any contact information',
            'view contact information',
            'create contact information',
            'edit contact information',
            'delete contact information',
            'restore contact information',
            'import contact information',
            'export contact information',
            'merge contacts',
            'view task statuses',
            'create task statuses',
            'edit task statuses',
            'delete task statuses',
            'restore task statuses',
            'force delete task statuses',
            'import task statuses',
            'export task statuses',
            'assign task statuses',
            'view any task',
            'view task',
            'create task',
            'edit task',
            'delete task',
            'restore task',
            'import task',
            'export task',
            'assign task',
            'change task status',
            'view order statuses',
            'create order statuses',
            'edit order statuses',
            'delete order statuses',
            'restore order statuses',
            'force delete order statuses',
            'import order statuses',
            'export order statuses',
            'assign order statuses',
            'view any order',
            'view order',
            'create order',
            'edit order',
            'delete order',
            'restore order',
            'import order',
            'export order',
            'assign order',
            'change order status',
            'view industries',
            'create industries',
            'edit industries',
            'delete industries',
            'restore industries',
            'force delete industries',
            'import industries',
            'export industries',
            'assign industries',
            'view companies',
            'create companies',
            'edit companies',
            'delete companies',
            'restore companies',
            'force delete companies',
            'import companies',
            'export companies',
            'change company industry',
            'merge companies',
            'view any plans',
            'view plans',
            'create plans',
            'edit plans',
            'view any addresses',
            'view addresses',
            'create addresses',
            'edit addresses',
            'delete addresses',
            'force delete addresses',
            'restore addresses',
            'import addresses',
            'export addresses',
            'assign address',
            'view any categories',
            'view categories',
            'create categories',
            'edit categories',
            'delete categories',
            'restore categories',
            'force delete categories',
            'import categories',
            'export categories',
            'assign category',
            'view any posts',
            'view posts',
            'create posts',
            'edit posts',
            'delete posts',
            'restore posts',
            'import posts',
            'export posts',
            'view any comments',
            'view comments',
            'create comments',
            'edit comments',
            'delete comments',
            'restore comments',
            'import comments',
            'export comments',
            'view any tags',
            'view tags',
            'create tags',
            'update tags',
            'delete tags',
            'restore tags',
            'import tags',
            'export tags',
            'view invoice statuses',
            'create invoice statuses',
            'edit invoice statuses',
            'delete invoice statuses',
            'restore invoice statuses',
            'force delete invoice statuses',
            'import invoice statuses',
            'export invoice statuses',
            'assign invoice statuses',
            'view any invoice',
            'view invoice',
            'create invoice',
            'edit invoice',
            'delete invoice',
            'restore invoice',
            'import invoice',
            'export invoice',
            'assign invoice',
            'change invoice status',
            'send invoices',
            'mark invoices as paid',
            'mark invoice as unpaid',
            'create invoice item',
            'edit invoice item',
            'delete invoice item',
            'restore invoice item',
            'import invoice item',
            'export invoice item',
            'view pipeline statuses',
            'create pipeline statuses',
            'edit pipeline statuses',
            'delete pipeline statuses',
            'restore pipeline statuses',
            'force delete pipeline statuses',
            'import pipeline statuses',
            'export pipeline statuses',
            'assign pipeline statuses',
            'view any pipeline',
            'view pipeline',
            'create pipeline',
            'edit pipeline',
            'delete pipeline',
            'restore pipeline',
            'import pipeline',
            'export pipeline',
            'assign pipeline',
            'change pipeline status',
            'view any pipeline stage',
            'view pipeline stage',
            'create pipeline stage',
            'edit pipeline stage',
            'delete pipeline stage',
            'restore pipeline stage',
            'import pipeline stage',
            'export pipeline stage',
            'assign pipeline stage',
            'view deal statuses',
            'create deal statuses',
            'edit deal statuses',
            'delete deal statuses',
            'restore deal statuses',
            'force delete deal statuses',
            'import deal statuses',
            'export deal statuses',
            'assign deal statuses',
            'view any deal',
            'view deal',
            'create deal',
            'edit deal',
            'delete deal',
            'restore deal',
            'import deal',
            'export deal',
            'assign deal',
            'change deal status',
            'view ticket priorities',
            'create ticket priorities',
            'edit ticket priorities',
            'delete ticket priorities',
            'restore ticket priorities',
            'force delete ticket priorities',
            'import ticket priorities',
            'export ticket priorities',
            'assign ticket priorities',
            'view ticket statuses',
            'create ticket statuses',
            'edit ticket statuses',
            'delete ticket statuses',
            'restore ticket statuses',
            'force delete ticket statuses',
            'import ticket statuses',
            'export ticket statuses',
            'assign ticket statuses',
            'view any ticket',
            'view ticket',
            'create ticket',
            'edit ticket',
            'delete ticket',
            'restore ticket',
            'import ticket',
            'export ticket',
            'assign ticket',
            'change ticket status',
            'change ticket priority',
            'view any labels',
            'view labels',
            'create labels',
            'edit labels',
            'delete labels',
            'restore labels',
            'import labels',
            'export labels',
            'assign labels',
            'view activities',
            'create activities',
            'delete activities',
            'restore activities',
            'export activities',
            'create interaction logs',
            'update interaction logs',
            'delete interaction logs',
            'view any attachments',
            'view attachments',
            'create attachments',
            'delete attachments',
            'restore attachments',
            'download attachments',
        ];
        $manager->givePermissionTo($managerPermissions);

        // Editor role - focused on content management
        $editor = Role::firstOrCreate(['name' => 'Editor']);
        $editorPermissions = [
            'view dashboard',
            'view statistics',
            'view own profile',
            'edit own profile',
            'delete own profile',
            'change own password',
            'view notifications',
            'view files',
            'upload files',
            'download files',
            'delete files',
            'view reports',
            'view task statuses',
            'view any contact information',
            'view contact information',
            'create contact information',
            'edit contact information',
            'delete contact information',
            'restore contact information',
            'create task statuses',
            'edit task statuses',
            'delete task statuses',
            'restore task statuses',
            'assign task statuses',
            'view any task',
            'view task',
            'create task',
            'edit task',
            'delete task',
            'restore task',
            'assign task',
            'change task status',
            'create order statuses',
            'edit order statuses',
            'delete order statuses',
            'restore order statuses',
            'assign order statuses',
            'view any order',
            'view order',
            'create order',
            'edit order',
            'delete order',
            'restore order',
            'assign order',
            'change order status',
            'view industries',
            'create industries',
            'edit industries',
            'delete industries',
            'restore industries',
            'assign industries',
            'view companies',
            'create companies',
            'edit companies',
            'delete companies',
            'restore companies',
            'change company industry',
            'view any addresses',
            'view addresses',
            'create addresses',
            'edit addresses',
            'delete addresses',
            'assign address',
            'view any categories',
            'view categories',
            'create categories',
            'edit categories',
            'delete categories',
            'restore categories',
            'assign category',
            'view any posts',
            'view posts',
            'create posts',
            'edit posts',
            'delete posts',
            'restore posts',
            'view any comments',
            'view comments',
            'create comments',
            'edit comments',
            'delete comments',
            'restore comments',
            'view any tags',
            'view tags',
            'create tags',
            'update tags',
            'delete tags',
            'restore tags',
            'view invoice statuses',
            'create invoice statuses',
            'edit invoice statuses',
            'delete invoice statuses',
            'restore invoice statuses',
            'assign invoice statuses',
            'view any invoice',
            'view invoice',
            'create invoice',
            'edit invoice',
            'delete invoice',
            'restore invoice',
            'assign invoice',
            'change invoice status',
            'send invoices',
            'view any invoice item',
            'view invoice item',
            'create invoice item',
            'edit invoice item',
            'delete invoice item',
            'restore invoice item',
            'create pipeline statuses',
            'edit pipeline statuses',
            'delete pipeline statuses',
            'restore pipeline statuses',
            'assign pipeline statuses',
            'view any pipeline',
            'view pipeline',
            'create pipeline',
            'edit pipeline',
            'delete pipeline',
            'restore pipeline',
            'assign pipeline',
            'change pipeline status',
            'view any pipeline stage',
            'view pipeline stage',
            'create pipeline stage',
            'edit pipeline stage',
            'delete pipeline stage',
            'restore pipeline stage',
            'assign pipeline stage',
            'create deal statuses',
            'edit deal statuses',
            'delete deal statuses',
            'restore deal statuses',
            'assign deal statuses',
            'view any deal',
            'view deal',
            'create deal',
            'edit deal',
            'delete deal',
            'restore deal',
            'assign deal',
            'change deal status',
            'view ticket priorities',
            'create ticket priorities',
            'edit ticket priorities',
            'delete ticket priorities',
            'restore ticket priorities',
            'assign ticket priorities',
            'view ticket statuses',
            'create ticket statuses',
            'edit ticket statuses',
            'delete ticket statuses',
            'restore ticket statuses',
            'assign ticket statuses',
            'view any ticket',
            'view ticket',
            'create ticket',
            'edit ticket',
            'delete ticket',
            'restore ticket',
            'assign ticket',
            'change ticket status',
            'change ticket priority',
            'view any labels',
            'view labels',
            'create labels',
            'edit labels',
            'delete labels',
            'restore labels',
            'assign labels',
            'view activities',
            'create activities',
            'delete activities',
            'create interaction logs',
            'update interaction logs',
            'view any attachments',
            'view attachments',
            'create attachments',
            'delete attachments',
            'download attachments',
        ];
        $editor->givePermissionTo($editorPermissions);

        // Viewer role - read-only access to most features
        $viewer = Role::firstOrCreate(['name' => 'Viewer']);
        $viewerPermissions = [
            'view dashboard',
            'view statistics',
            'view charts',
            'view users',
            'view own profile',
            'edit own profile',
            'delete own profile',
            'change own password',
            'view notifications',
            'view reports',
            'view files',
            'download files',
            'view contact information',
            'view task statuses',
            'view any task',
            'view task',
            'view order statuses',
            'view any order',
            'view order',
            'view industries',
            'view companies',
            'view any addresses',
            'view addresses',
            'view any categories',
            'view categories',
            'view any posts',
            'view posts',
            'view any comments',
            'view comments',
            'view any tags',
            'view tags',
            'view any invoice',
            'view invoice',
            'view any invoice item',
            'view invoice item',
            'view any pipeline',
            'view pipeline',
            'view any pipeline stage',
            'view pipeline stage',
            'view any deal',
            'view deal',
            'view ticket priorities',
            'view ticket statuses',
            'view any ticket',
            'view ticket',
            'view any labels',
            'view labels',
            'view activities',
            'view any attachments',
            'view attachments',
            'download attachments',
        ];
        $viewer->givePermissionTo($viewerPermissions);

        // Moderator role - can manage content and moderate users
        $moderator = Role::firstOrCreate(['name' => 'Moderator']);
        $moderatorPermissions = [
            'view dashboard',
            'view statistics',
            'view charts',
            'view users',
            'edit users',
            'view own profile',
            'edit own profile',
            'delete own profile',
            'change own password',
            'view notifications',
            'create notifications',
            'send notifications',
            'view any activity logs',
            'view activity logs',
            'view files',
            'upload files',
            'download files',
            'delete files',
            'view reports',
            'view task statuses',
            'create task statuses',
            'edit task statuses',
            'view any task',
            'view task',
            'create task',
            'edit task',
            'view order statuses',
            'create order statuses',
            'edit order statuses',
            'view any order',
            'view order',
            'create order',
            'edit order',
            'view any contact information',
            'view contact information',
            'create contact information',
            'edit contact information',
            'view industries',
            'create industries',
            'edit industries',
            'view companies',
            'create companies',
            'edit companies',
            'view any addresses',
            'view addresses',
            'create addresses',
            'edit addresses',
            'view any categories',
            'view categories',
            'create categories',
            'edit categories',
            'view any posts',
            'view posts',
            'create posts',
            'edit posts',
            'view any comments',
            'view comments',
            'create comments',
            'edit comments',
            'view any tags',
            'view tags',
            'create tags',
            'update tags',
            'view any invoice',
            'view invoice',
            'create invoice',
            'edit invoice',
            'view any invoice item',
            'view invoice item',
            'create invoice item',
            'edit invoice item',
            'view any pipeline',
            'view pipeline',
            'create pipeline',
            'edit pipeline',
            'view any pipeline stage',
            'view pipeline stage',
            'create pipeline stage',
            'edit pipeline stage',
            'view any deal',
            'view deal',
            'create deal',
            'edit deal',
            'view ticket priorities',
            'create ticket priorities',
            'edit ticket priorities',
            'view ticket statuses',
            'create ticket statuses',
            'edit ticket statuses',
            'view any ticket',
            'view ticket',
            'create ticket',
            'edit ticket',
            'view any labels',
            'view labels',
            'create labels',
            'edit labels',
            'assign labels',
            'view activities',
            'create activities',
            'delete activities',
            'restore activities',
            'create interaction logs',
            'update interaction logs',
            'view any attachments',
            'view attachments',
            'create attachments',
            'delete attachments',
            'download attachments',
        ];
        $moderator->givePermissionTo($moderatorPermissions);

        // Support role - customer support focused
        $support = Role::firstOrCreate(['name' => 'Support']);
        $supportPermissions = [
            'view dashboard',
            'view statistics',
            'view users',
            'view own profile',
            'edit own profile',
            'delete own profile',
            'change own password',
            'view other profiles',
            'view notifications',
            'create notifications',
            'send notifications',
            'view any activity logs',
            'view activity logs',
            'view reports',
            'view files',
            'download files',
            'view any contact information',
            'view contact information',
            'create contact information',
            'edit contact information',
            'delete contact information',
            'restore contact information',
            'import contact information',
            'export contact information',
            'view task statuses',
            'create task statuses',
            'edit task statuses',
            'delete task statuses',
            'restore task statuses',
            'import task statuses',
            'export task statuses',
            'assign task statuses',
            'view task',
            'view any task',
            'create task',
            'edit task',
            'delete task',
            'restore task',
            'import task',
            'export task',
            'assign task',
            'change task status',
            'view order statuses',
            'create order statuses',
            'edit order statuses',
            'delete order statuses',
            'restore order statuses',
            'import order statuses',
            'export order statuses',
            'assign order statuses',
            'view order',
            'view any order',
            'create order',
            'edit order',
            'delete order',
            'restore order',
            'import order',
            'export order',
            'assign order',
            'change order status',
            'view industries',
            'create industries',
            'edit industries',
            'delete industries',
            'restore industries',
            'import industries',
            'export industries',
            'assign industries',
            'view companies',
            'create companies',
            'edit companies',
            'delete companies',
            'restore companies',
            'import companies',
            'export companies',
            'change company industry',
            'view any addresses',
            'view addresses',
            'create addresses',
            'edit addresses',
            'delete addresses',
            'restore addresses',
            'import addresses',
            'export addresses',
            'assign address',
            'view any categories',
            'view categories',
            'create categories',
            'edit categories',
            'delete categories',
            'restore categories',
            'import categories',
            'export categories',
            'assign category',
            'view any posts',
            'view posts',
            'create posts',
            'edit posts',
            'delete posts',
            'restore posts',
            'import posts',
            'export posts',
            'view any comments',
            'view comments',
            'create comments',
            'edit comments',
            'delete comments',
            'restore comments',
            'import comments',
            'export comments',
            'view any tags',
            'view tags',
            'create tags',
            'update tags',
            'delete tags',
            'restore tags',
            'import tags',
            'export tags',
            'view invoice statuses',
            'create invoice statuses',
            'edit invoice statuses',
            'delete invoice statuses',
            'restore invoice statuses',
            'import invoice statuses',
            'export invoice statuses',
            'assign invoice statuses',
            'view any invoice',
            'view invoice',
            'create invoice',
            'edit invoice',
            'delete invoice',
            'restore invoice',
            'import invoice',
            'export invoice',
            'assign invoice',
            'change invoice status',
            'send invoices',
            'mark invoices as paid',
            'mark invoice as unpaid',
            'view any invoice item',
            'view invoice item',
            'create invoice item',
            'edit invoice item',
            'delete invoice item',
            'restore invoice item',
            'import invoice item',
            'export invoice item',
            'view pipeline statuses',
            'create pipeline statuses',
            'edit pipeline statuses',
            'delete pipeline statuses',
            'restore pipeline statuses',
            'import pipeline statuses',
            'export pipeline statuses',
            'assign pipeline statuses',
            'view any pipeline',
            'view pipeline',
            'create pipeline',
            'edit pipeline',
            'delete pipeline',
            'restore pipeline',
            'import pipeline',
            'export pipeline',
            'assign pipeline',
            'change pipeline status',
            'view any pipeline stage',
            'view pipeline stage',
            'create pipeline stage',
            'edit pipeline stage',
            'delete pipeline stage',
            'restore pipeline stage',
            'import pipeline stage',
            'export pipeline stage',
            'assign pipeline stage',
            'view deal statuses',
            'create deal statuses',
            'edit deal statuses',
            'delete deal statuses',
            'restore deal statuses',
            'import deal statuses',
            'export deal statuses',
            'assign deal statuses',
            'view any deal',
            'view deal',
            'create deal',
            'edit deal',
            'delete deal',
            'restore deal',
            'import deal',
            'export deal',
            'assign deal',
            'change deal status',
            'view ticket priorities',
            'create ticket priorities',
            'edit ticket priorities',
            'delete ticket priorities',
            'restore ticket priorities',
            'import ticket priorities',
            'export ticket priorities',
            'assign ticket priorities',
            'view ticket statuses',
            'create ticket statuses',
            'edit ticket statuses',
            'delete ticket statuses',
            'restore ticket statuses',
            'import ticket statuses',
            'export ticket statuses',
            'assign ticket statuses',
            'view ticket',
            'view any ticket',
            'create ticket',
            'edit ticket',
            'delete ticket',
            'restore ticket',
            'import ticket',
            'export ticket',
            'assign ticket',
            'change ticket status',
            'change ticket priority',
            'view any labels',
            'view labels',
            'create labels',
            'edit labels',
            'delete labels',
            'restore labels',
            'import labels',
            'export labels',
            'assign labels',
            'view activities',
            'create activities',
            'delete activities',
            'restore activities',
            'export activities',
            'create interaction logs',
            'update interaction logs',
            'delete interaction logs',
            'view any attachments',
            'view attachments',
            'create attachments',
            'delete attachments',
            'download attachments',
        ];
        $support->givePermissionTo($supportPermissions);

        // Analyst role - focused on data and reports
        $analyst = Role::firstOrCreate(['name' => 'Analyst']);
        $analystPermissions = [
            'view dashboard',
            'view statistics',
            'view charts',
            'export dashboard data',
            'view users',
            'export users',
            'view own profile',
            'edit own profile',
            'delete own profile',
            'change own password',
            'view any activity logs',
            'view activity logs',
            'export activity logs',
            'view reports',
            'create reports',
            'edit reports',
            'export reports',
            'schedule reports',
            'view files',
            'download files',
            'view audit trail',
            'export audit trail',
            'view any contact information',
            'view contact information',
            'export contact information',
            'view task statuses',
            'export task statuses',
            'assign task statuses',
            'view any task',
            'view task',
            'export task',
            'assign task',
            'view order statuses',
            'export order statuses',
            'assign order statuses',
            'view any order',
            'view order',
            'export order',
            'assign order',
            'view industries',
            'export industries',
            'assign industries',
            'view companies',
            'export companies',
            'change company industry',
            'view any addresses',
            'view addresses',
            'export addresses',
            'view any categories',
            'view categories',
            'export categories',
            'assign category',
            'view any posts',
            'view posts',
            'export posts',
            'view any comments',
            'view comments',
            'export comments',
            'view any tags',
            'view tags',
            'view any invoice',
            'view invoice',
            'export invoice',
            'assign invoice',
            'view any invoice item',
            'view invoice item',
            'export invoice item',
            'view any pipeline',
            'view pipeline',
            'export pipeline',
            'assign pipeline',
            'view any pipeline stage',
            'view pipeline stage',
            'export pipeline stage',
            'assign pipeline stage',
            'view any deal',
            'view deal',
            'export deal',
            'assign deal',
            'view ticket priorities',
            'export ticket priorities',
            'assign ticket priorities',
            'view ticket statuses',
            'export ticket statuses',
            'assign ticket statuses',
            'view any ticket',
            'view ticket',
            'export ticket',
            'assign ticket',
            'view any labels',
            'view labels',
            'export labels',
            'view activities',
            'export activities',
        ];
        $analyst->givePermissionTo($analystPermissions);

        // User role - basic permissions for regular users
        $user = Role::firstOrCreate(['name' => 'User']);
        $userPermissions = [
            'view dashboard',
            'view own profile',
            'edit own profile',
            'delete own profile',
            'change own password',
            'view notifications',
            'view files',
            'upload files',
            'download files',
            'view any contact information',
            'view contact information',
            'view task statuses',
            'view any task',
            'view task',
            'view order statuses',
            'view any order',
            'view order',
            'view industries',
            'view companies',
            'view any plans',
            'view plans',
            'view any addresses',
            'view addresses',
            'view categories',
            'view posts',
            'view comments',
            'view tags',
            'view any invoice',
            'view invoice',
            'view any invoice item',
            'view invoice item',
            'view any pipeline',
            'view pipeline',
            'view any pipeline stage',
            'view pipeline stage',
            'view any deal',
            'view deal',
            'view ticket priorities',
            'view ticket statuses',
            'view any ticket',
            'view ticket',
            'view any labels',
            'view labels',
            'view activities',
            'view calendar',
        ];
        $user->givePermissionTo($userPermissions);

        // Guest role - minimal read-only access
        $guest = Role::firstOrCreate(['name' => 'Guest']);
        $guestPermissions = [
            'view dashboard',
            'view task statuses',
            'view any task',
            'view task',
            'view order statuses',
            'view any order',
            'view order',
            'view industries',
            'view companies',
            'view categories',
            'view posts',
            'view comments',
            'view tags',
            'view any invoice',
            'view invoice',
            'view any invoice item',
            'view invoice item',
            'view any pipeline',
            'view pipeline',
            'view any pipeline stage',
            'view pipeline stage',
            'view any deal',
            'view deal',
            'view ticket priorities',
            'view ticket statuses',
            'view any ticket',
            'view ticket',
            'view any labels',
            'view labels',
        ];
        $guest->givePermissionTo($guestPermissions);

        $this->command->info('Roles and permissions created successfully!');
        $this->command->info('');
        $this->command->info('Roles created:');
        $this->command->info('1. Super Admin - Full system access (all permissions)');
        $this->command->info('2. Admin - Administrative access (most permissions except critical system ops)');
        $this->command->info('3. Manager - User and content management');
        $this->command->info('4. Editor - Content creation and management');
        $this->command->info('5. Viewer - Read-only access to most features');
        $this->command->info('6. Moderator - Content and user moderation');
        $this->command->info('7. Support - Customer support operations');
        $this->command->info('8. Analyst - Data analysis and reporting');
        $this->command->info('9. User - Basic user permissions');
        $this->command->info('10. Guest - Minimal read-only access');
        $this->command->info('');
        $this->command->info('Total permissions created: '.Permission::count());
        $this->command->info('');
        $this->command->info('Permission categories:');
        $this->command->info('- Dashboard & Statistics');
        $this->command->info('- User Management');
        $this->command->info('- Role & Permission Management');
        $this->command->info('- Profile Management');
        $this->command->info('- Settings & Configuration');
        $this->command->info('- Notifications');
        $this->command->info('- Activity Logs & Audit Trail');
        $this->command->info('- Reports & Analytics');
        $this->command->info('- File Management');
        $this->command->info('- Backup & Restore');
        $this->command->info('- API Management');
        $this->command->info('- System Maintenance');
        $this->command->info('- Contact Information');
        $this->command->info('- Task Statuses');
        $this->command->info('- Tasks');
        $this->command->info('- Order Statuses');
        $this->command->info('- Orders');
        $this->command->info('- Industries');
        $this->command->info('- Companies');
        $this->command->info('- Plans');
        $this->command->info('- Addresses');
        $this->command->info('- Categories');
        $this->command->info('- Posts');
        $this->command->info('- Comments');
        $this->command->info('- Tags');
        $this->command->info('- Invoice Statuses');
        $this->command->info('- Invoices');
        $this->command->info('- Invoice Items');
        $this->command->info('- Pipeline Statuses');
        $this->command->info('- Pipelines');
        $this->command->info('- Pipeline Stages');
        $this->command->info('- Deal Statuses');
        $this->command->info('- Deals');
        $this->command->info('- Ticket Priorities');
        $this->command->info('- Ticket Statuses');
        $this->command->info('- Tickets');
        $this->command->info('- Labels');
        $this->command->info('- Activities');
        $this->command->info('- Calendars');
        $this->command->info('- Attachments');
    }
}
